/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cesar
 */
public class Main extends javax.swing.JFrame {

    Lista lista1 = new Lista();
    Lista lista2 = new Lista();
    String result = "";
    
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PrimerNumero = new javax.swing.JTextField();
        SegundoNumero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Calcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Resultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SegundoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SegundoNumeroActionPerformed(evt);
            }
        });

        jLabel1.setText("Primer Número");

        jLabel2.setText("Segundo Número");

        Calcular.setText("Calcular");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });

        Resultado.setColumns(20);
        Resultado.setRows(5);
        jScrollPane1.setViewportView(Resultado);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(PrimerNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                        .addComponent(SegundoNumero)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(PrimerNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SegundoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SegundoNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SegundoNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SegundoNumeroActionPerformed

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        this.result = "";
        String[] primero =  PrimerNumero.getText().split("");
        String[] segundo  = SegundoNumero.getText().split("");
        
        //Obtener cabeza 1
        String num = "";
        int iterador = 0;
        int size1 = 0;
        if(primero.length%4 == 0){
            num = primero[0]+primero[1]+primero[2]+primero[3];
            iterador = 4;
            size1 = primero.length/4;
        }else{
            int rest = primero.length%4;
            switch(rest){
                case 1:
                    num = primero[0];
                    iterador = 1;
                    size1 = 1+(primero.length/4);
                    break;
                case 2:
                    num = primero[0]+primero[1];
                    iterador = 2;
                    size1 = 1+(primero.length/4);
                    break;
                case 3:
                    num = primero[0]+primero[1]+primero[2];
                    iterador = 3;
                    size1 = 1+(primero.length/4);
                    break;
            }
        }
        Nodo nuevo1 = new Nodo(Integer.parseInt(num));
        lista1.setCabeza(nuevo1); 
        
        //LLenar la lista 1
        lista1.llenarLista(primero,lista1.getCabeza(),iterador);
        
        
        //Obtener cabeza 2
        num = "";
        iterador = 0;
        int size2 = 0;
        if(segundo.length%4 == 0){
            num = segundo[0]+segundo[1]+segundo[2]+segundo[3];
            iterador = 4;
            size2 = segundo.length/4;
        }else{
            int rest = segundo.length%4;
            switch(rest){
                case 1:
                    num = segundo[0];
                    iterador = 1;
                    size2 = 1+(segundo.length/4);
                    break;
                case 2:
                    num = segundo[0]+segundo[1];
                    iterador = 2;
                    size2 = 1+(segundo.length/4);
                    break;
                case 3:
                    num = segundo[0]+segundo[1]+segundo[2];
                    iterador = 3;
                    size2 = 1+(segundo.length/4);
                    break;
            }
        }
        Nodo nuevo2 = new Nodo(Integer.parseInt(num));
        lista2.setCabeza(nuevo2); 
        
        //LLenar la lista 2
        lista2.llenarLista(segundo,lista2.getCabeza(),iterador);
        
        
        //igualar tamaños de la lista
        if(size1 != size2){
            if(size1 < size2){
                for(int i=0;i<size2-size1;i++){
                    Nodo nuevo = new Nodo(0);
                    lista1.getCabeza().setAnterior(nuevo);
                    nuevo.setSiguiente(lista1.getCabeza());
                    lista1.setCabeza(nuevo);
                }
            }else{
                for(int i=0;i<size1-size2;i++){
                    Nodo nuevo = new Nodo(0);
                    lista2.getCabeza().setAnterior(nuevo);
                    nuevo.setSiguiente(lista2.getCabeza());
                    lista2.setCabeza(nuevo);
                }
            }
        }
        
        lista1.encontrarCola(lista1.getCabeza());
        lista2.encontrarCola(lista2.getCabeza());
        
        sumar(lista1.getCola(),lista2.getCola(),0);
        lista1.mostrarLista(lista1.getCabeza());
        lista2.mostrarLista(lista2.getCabeza());
        acomodarResultado();
        this.Resultado.setText(lista1.getLista()+"\n"+lista2.getLista()+"\n"+"________________________________________"+"\n"+result);
    }//GEN-LAST:event_CalcularActionPerformed
    
    private void acomodarResultado(){
        int size = this.result.length();
        String newResult = "";
        if(size%4 == 0){
            for(int i=size;i>=4;i-=4){
                newResult += this.result.substring(i-4, i);
            }
        }else{
            newResult += this.result.substring(4*((int)size/4), size);
            for(int i=4*((int)size/4);i>=4;i-=4){
                newResult += this.result.substring(i-4, i);
            }
        }
        result = newResult;
    }
    
    private void sumar(Nodo nodoLista1, Nodo nodoLista2,int lleva){
        if(nodoLista1 != null && nodoLista2 != null){
            int sum = nodoLista1.getNumero() + nodoLista2.getNumero() + lleva;
            if(sum/10 == 0){
                lleva = 0;
                this.result += "0"+"0"+"0"+sum;
            }else if(sum/100 == 0){
                lleva = 0;
                this.result += "0"+"0"+sum;
            }else if(sum/1000 == 0){
                lleva = 0;
                this.result += "0"+sum;
            }else if(sum/10000 == 0){
                lleva = 0;
                this.result += sum;
            }else if(sum/100000 == 0){
                lleva = sum/10000;
                String aux = sum+"";
                this.result += aux.substring(1);
            }
            sumar(nodoLista1.getAnterior(),nodoLista2.getAnterior(),lleva);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular;
    private javax.swing.JTextField PrimerNumero;
    private javax.swing.JTextArea Resultado;
    private javax.swing.JTextField SegundoNumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
